<a href="https://colab.research.google.com/github/vcdemy/20231026/blob/main/20231027%E7%AD%86%E8%A8%98.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 20231027筆記

## 綜合練習 03

In [1]:
import folium
import requests

In [2]:
url = "https://tcgbusfs.blob.core.windows.net/dotapp/youbike/v2/youbike_immediate.json"

In [ ]:
data = requests.get(url, verify=False).json()

In [8]:
m = folium.Map(location=[25.0330, 121.5654], zoom_start=16)

In [ ]:
folium.Marker(location=[25.0330, 121.5654], popup="台北市", icon=folium.Icon(color="red")).add_to(m)

In [9]:
for x in data:
    folium.Marker(location=[x['lat'], x['lng']], popup=x['sna']).add_to(m)

In [10]:
m

## 基本語法

* if statements (條件式)
* loops (迴圈)
* functions (函式)
* exception handling (例外處理)

### 條件式(if)

In [13]:
a = 3
b = 4

In [14]:
if a > b:
  print("a 大於 b")

In [15]:
if a > b:
  print("a 大於 b")
else:
  print("a 沒有大於 b")

a 沒有大於 b


In [16]:
if a > b:
  print("a 大於 b")
elif a < b:
  print("a 小於 b")
else:
  print("a 等於 b")

a 小於 b


## print() v.s., input()

In [88]:
x = input('請輸入您的大名: ')
print('Hello,', x, '!')

請輸入您的大名: Victor
Hello, Victor !


In [91]:
x = input('請輸入一個數字: ')
if int(x) > 10:
  print('您輸入的數字大於 10!')
else:
  print('您輸入的數字大於 10!')

請輸入一個數字: 11
您輸入的數字大於 10!


In [90]:
print?

In [19]:
for i in range(5):
  print(i, end=", ")

0, 1, 2, 3, 4, 

In [22]:
x = 1234
y = 1.23
z = True
s = "Hi"

In [23]:
print(x, y, z, s)

1234 1.23 True Hi


In [24]:
x + s

TypeError: ignored

In [25]:
str(x) + s

'1234Hi'

In [26]:
x + int(s)

ValueError: ignored

In [27]:
u = '10'

In [28]:
x + u

TypeError: ignored

In [29]:
x + int(u)

1244

## 練習

計算BMI並回傳健康狀況。

$ bmi = \frac{體重(公斤)}{身高(公尺)^2} $

<pre>
$ bmi = \frac{體重(公斤)}{身高(公尺)^2} $
</pre>

|bmi|身體狀況|
|:-:|:-:|
|bmi<18.5|體重過輕|
|18.5<=bmi<24|正常體重|
|bmi>=24|體重過重|

<pre>
|bmi|身體狀況|
|:-:|:-:|
|bmi<18.5|體重過輕|
|18.5<=bmi<24|正常體重|
|bmi>=24|體重過重|
</pre>

In [30]:
h = 1.83
w = 80

In [31]:
bmi = w/h**2

In [32]:
bmi

23.888440980620498

In [35]:
round(bmi, 2)

23.89

In [38]:
if bmi < 18.5:
  print("體重過輕")
elif bmi >= 24:
  print("體重太重")
else:
  print("正常體重")

正常體重


In [37]:
if bmi < 18.5:
  print("體重過輕")
elif 18.5 <= bmi < 24:
  print("正常體重")
else:
  print("體重太重")

正常體重


In [42]:
def health01(h, w):
  bmi = w/h**2
  if bmi < 18.5:
    print("體重過輕")
  elif bmi >= 24:
    print("體重太重")
  else:
    print("正常體重")

In [41]:
def health02(h, w):
  bmi = w/h**2
  if bmi < 18.5:
    return "體重過輕"
  elif bmi >= 24:
    return "體重太重"
  else:
    return "正常體重"

In [43]:
health01(1.83, 80)

正常體重


In [44]:
health02(1.83, 80)

'正常體重'

In [45]:
x = health01(1.83, 80)

正常體重


In [46]:
y = health02(1.83, 80)

In [47]:
x

In [48]:
y

'正常體重'

### 迴圈

In [51]:
for i in range(3):
  print('開始')
  print(i)
  print('結束')

開始
0
結束
開始
1
結束
開始
2
結束


In [52]:
for i in range(3):
  print('開始')
  print(i)
print('結束')

開始
0
開始
1
開始
2
結束


In [53]:
x = list('abcde')

In [54]:
x

['a', 'b', 'c', 'd', 'e']

In [56]:
for i in x:
  print(i)

a
b
c
d
e


In [57]:
d = {}

In [58]:
d['cat'] = '貓咪'
d['dog'] = '狗狗'
d['rabbit'] = '兔兔'

In [59]:
d

{'cat': '貓咪', 'dog': '狗狗', 'rabbit': '兔兔'}

In [60]:
for i in d:
  print(i)

cat
dog
rabbit


In [62]:
for i in d:
  print(i, '==>', d[i])

cat ==> 貓咪
dog ==> 狗狗
rabbit ==> 兔兔


## 'in' operator

In [63]:
s = "JSON (JavaScript Object Notation, pronounced /ˈdʒeɪsən/; also /ˈdʒeɪˌsɒn/) is an open standard file format and data interchange format that uses human-readable text to store and transmit data objects consisting of attribute–value pairs and arrays (or other serializable values). It is a common data format with diverse uses in electronic data interchange, including that of web applications with servers."

In [64]:
s

'JSON (JavaScript Object Notation, pronounced /ˈdʒeɪsən/; also /ˈdʒeɪˌsɒn/) is an open standard file format and data interchange format that uses human-readable text to store and transmit data objects consisting of attribute–value pairs and arrays (or other serializable values). It is a common data format with diverse uses in electronic data interchange, including that of web applications with servers.'

In [65]:
s.split()

['JSON',
 '(JavaScript',
 'Object',
 'Notation,',
 'pronounced',
 '/ˈdʒeɪsən/;',
 'also',
 '/ˈdʒeɪˌsɒn/)',
 'is',
 'an',
 'open',
 'standard',
 'file',
 'format',
 'and',
 'data',
 'interchange',
 'format',
 'that',
 'uses',
 'human-readable',
 'text',
 'to',
 'store',
 'and',
 'transmit',
 'data',
 'objects',
 'consisting',
 'of',
 'attribute–value',
 'pairs',
 'and',
 'arrays',
 '(or',
 'other',
 'serializable',
 'values).',
 'It',
 'is',
 'a',
 'common',
 'data',
 'format',
 'with',
 'diverse',
 'uses',
 'in',
 'electronic',
 'data',
 'interchange,',
 'including',
 'that',
 'of',
 'web',
 'applications',
 'with',
 'servers.']

In [66]:
set(s.split())

{'(JavaScript',
 '(or',
 '/ˈdʒeɪsən/;',
 '/ˈdʒeɪˌsɒn/)',
 'It',
 'JSON',
 'Notation,',
 'Object',
 'a',
 'also',
 'an',
 'and',
 'applications',
 'arrays',
 'attribute–value',
 'common',
 'consisting',
 'data',
 'diverse',
 'electronic',
 'file',
 'format',
 'human-readable',
 'in',
 'including',
 'interchange',
 'interchange,',
 'is',
 'objects',
 'of',
 'open',
 'other',
 'pairs',
 'pronounced',
 'serializable',
 'servers.',
 'standard',
 'store',
 'text',
 'that',
 'to',
 'transmit',
 'uses',
 'values).',
 'web',
 'with'}

In [67]:
'JSON' in s

True

In [68]:
'Python' in s

False

In [69]:
'Javascript' in s

False

In [70]:
'JavaScript'  in s

True

In [71]:
d

{'cat': '貓咪', 'dog': '狗狗', 'rabbit': '兔兔'}

In [72]:
'dog' in d

True

In [73]:
'狗狗' in d

False

### 例外處理 (Exception Handling)

In [80]:
def add(a, b):
  print(f"{a} + {b} = {a+b}")

def sub(a, b):
  print(f"{a} - {b} = {a-b}")

def mul(a, b):
  print(f"{a} x {b} = {a*b}")

def div(a, b):
  print(f"{a} / {b} = {a/b}")

In [82]:
fns = [add, sub, div, mul]

In [83]:
for fn in fns:
  fn(1, 2)

1 + 2 = 3
1 - 2 = -1
1 / 2 = 0.5
1 x 2 = 2


In [84]:
for fn in fns:
  fn(1, 0)

1 + 0 = 1
1 - 0 = 1


ZeroDivisionError: ignored

In [85]:
for fn in fns:
  try:
    fn(1, 0)
  except Exception as e:
    print(e.args)

1 + 0 = 1
1 - 0 = 1
('division by zero',)
1 x 0 = 0


In [86]:
for fn in fns:
  try:
    fn(1, 0)
  except Exception as e:
    print('程式出錯了呦')

1 + 0 = 1
1 - 0 = 1
程式出錯了呦
1 x 0 = 0


In [87]:
for fn in fns:
  try:
    fn(1, 0)
  except:
    pass

1 + 0 = 1
1 - 0 = 1
1 x 0 = 0


## 資料分析基礎

* numpy ==> 科學運算基礎套件
* matplotlib ==> 繪圖基礎套件
* pandas ==> 資料分析基礎套件

套件載入慣例：

```python
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
```

<pre>
```python
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
```
</pre>

## numpy (Numerical Python)

* ndarray
* ufunc

In [92]:
import numpy as np

### ndarray

In [93]:
x = [1, 2, 3]
y = [4, 5, 6]

In [94]:
x + y

[1, 2, 3, 4, 5, 6]

In [95]:
x * 2

[1, 2, 3, 1, 2, 3]

In [96]:
x1 = np.array(x)
y1 = np.array(y)

In [97]:
x1

array([1, 2, 3])

In [98]:
y1

array([4, 5, 6])

In [99]:
x1 + y1

array([5, 7, 9])

In [100]:
x1 * 2

array([2, 4, 6])

### ufunc (Universal Functions)

In [101]:
import math

In [103]:
math.pi

3.141592653589793

In [102]:
math.sin(math.pi/2)

1.0

In [105]:
math.sin(x)

TypeError: ignored

In [106]:
np.pi

3.141592653589793

In [107]:
np.sin(np.pi/2)

1.0

In [108]:
np.sin(x)

array([0.84147098, 0.90929743, 0.14112001])

In [109]:
np.sin(x1)

array([0.84147098, 0.90929743, 0.14112001])

## 常用的Python影像處理套件

* pillow (PilImage)
* OpenCV (ndarray)
* Scikit-Image (ndarray)

### ndarray 的 indexing 跟 slicing

In [111]:
M = np.arange(25)

In [112]:
M

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [113]:
M.dtype

dtype('int64')

In [114]:
M.size

25

In [115]:
M.shape

(25,)

In [116]:
M.shape = 5, 5

In [117]:
M

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [118]:
N = [[ 0,  1,  2,  3,  4],
     [ 5,  6,  7,  8,  9],
     [10, 11, 12, 13, 14],
     [15, 16, 17, 18, 19],
     [20, 21, 22, 23, 24]]

In [119]:
len(N)

5

In [121]:
N[2]

[10, 11, 12, 13, 14]

In [122]:
N[2][2]

12

In [123]:
M[2][2]

12

In [124]:
M[2, 2]

12

In [125]:
M[1:3, 1:3]

array([[ 6,  7],
       [11, 12]])

In [127]:
!pip install gradio

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.3/20.3 MB 62.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 92.9/92.9 kB 9.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 299.2/299.2 kB 27.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.7/75.7 kB 8.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 302.0/302.0 kB 29.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 138.7/138.7 kB 14.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.7/45.7 kB 4.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.5/59.5 kB 6.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.9/129.9 kB 14.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.3/58.3 kB 5.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.0/67.0 kB 7.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.0/76.0 kB 8.8 MB/

In [10]:
import gradio as gr

In [3]:
import cv2

In [8]:
def process(image):
  image[:,:,1:] = 0
  return image

In [9]:
gr.Interface(process, 'image', 'image').launch()

Setting queue=True in a Colab notebook requires sharing enabled. Setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
Running on public URL: https://36612573f8aca7fc17.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)


## 字串跟list的翻轉

In [11]:
s = 'abc'

In [12]:
s[::-1]

'cba'

In [13]:
v = [1, 2, 3]

In [14]:
v[::-1]

[3, 2, 1]

## OpenCV基本操作

In [15]:
import cv2

In [18]:
import plotly.express as px

In [16]:
img = cv2.imread('lin03.jpg')

In [17]:
img.shape

(670, 1024, 3)

In [19]:
px.imshow(img)